![Imgur](https://i.imgur.com/J8Uf3wJ.png)

# What is **Missing Values**?

![](https://i.imgur.com/om4KGrq.png)

# Why Missing Values are Problematic?

![](https://i.imgur.com/Xnm4YLR.png)

# 📊 Data Used
![Imgur](https://i.imgur.com/olNuhpz.png)

In [ ]:
import pandas as pd

golf_dataset = pd.read_csv("/kaggle/input/golf-play-extended/L02_DataPreprocessing/golf_dataset_mini_lotsofmissingvalues.csv")
df = golf_dataset.copy()

df

     Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.1      99.0   0.0     rainy         0.14
1   08-02        1      0.0  26.4       NaN   0.0     sunny          NaN
2   08-03        2      0.0   NaN      96.0   0.0     rainy         0.21
3   08-04        3      0.0  24.1      68.0   0.0  overcast         0.68
4   08-05        4      NaN  24.7      98.0   0.0     rainy         0.20
5   08-06        5      0.0  26.5      98.0   0.0       NaN         0.32
6   08-07        6      0.0  27.6      78.0   0.0     rainy         0.72
7   08-08        0      0.0  28.2       NaN   0.0     rainy         0.61
8   08-09        1      0.0  27.1      70.0   0.0  overcast          NaN
9   08-10        2      1.0  26.7      75.0   NaN     sunny         0.54
10  08-11        3      0.0   NaN       NaN   0.0       NaN          NaN
11  08-12        4      NaN  24.3      77.0   0.0  overcast         0.67
12  08-13        5      0.0  23.1      77.0   1.0     sunny         0.66
13  08-14        6      0.0  22.4      89.0   1.0     rainy         0.38
14  08-15        0      0.0   NaN      80.0   1.0     sunny         0.46
15  08-16        1      0.0  26.5      88.0   1.0     rainy          NaN
16  08-17        2      0.0  28.6      76.0   0.0       NaN         0.52
17  08-18        3      0.0   NaN       NaN   NaN     rainy          NaN
18  08-19        4      0.0  27.0      73.0   1.0  overcast         0.62
19  08-20        5      0.0  26.9      73.0   0.0     sunny         0.81

# Method for Handling Missing Values

![](https://i.imgur.com/fkxzzKV.png)

#  ❯ Listwise Deletion
![Imgur](https://i.imgur.com/JAX1lcO.png)

In [ ]:
# Delete rows with 3 or more missing values
df.dropna(thresh=df.shape[1]-3+1, inplace=True)

df

     Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.1      99.0   0.0     rainy         0.14
1   08-02        1      0.0  26.4       NaN   0.0     sunny          NaN
2   08-03        2      0.0   NaN      96.0   0.0     rainy         0.21
3   08-04        3      0.0  24.1      68.0   0.0  overcast         0.68
4   08-05        4      NaN  24.7      98.0   0.0     rainy         0.20
5   08-06        5      0.0  26.5      98.0   0.0       NaN         0.32
6   08-07        6      0.0  27.6      78.0   0.0     rainy         0.72
7   08-08        0      0.0  28.2       NaN   0.0     rainy         0.61
8   08-09        1      0.0  27.1      70.0   0.0  overcast          NaN
9   08-10        2      1.0  26.7      75.0   NaN     sunny         0.54
11  08-12        4      NaN  24.3      77.0   0.0  overcast         0.67
12  08-13        5      0.0  23.1      77.0   1.0     sunny         0.66
13  08-14        6      0.0  22.4      89.0   1.0     rainy         0.38
14  08-15        0      0.0   NaN      80.0   1.0     sunny         0.46
15  08-16        1      0.0  26.5      88.0   1.0     rainy          NaN
16  08-17        2      0.0  28.6      76.0   0.0       NaN         0.52
18  08-19        4      0.0  27.0      73.0   1.0  overcast         0.62
19  08-20        5      0.0  26.9      73.0   0.0     sunny         0.81

#  ❯ Imputation Using Mean / Median / Mode
![Imgur](https://i.imgur.com/y9jK0uK.png)

In [ ]:
# Imputation on Holiday using Mode, and on Humidity using Mean
df['Holiday'].fillna(df['Holiday'].mode()[0], inplace=True)
df['Humidity'].fillna(df['Humidity'].mean(), inplace=True)

df

     Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.1   99.0000   0.0     rainy         0.14
1   08-02        1      0.0  26.4   82.1875   0.0     sunny          NaN
2   08-03        2      0.0   NaN   96.0000   0.0     rainy         0.21
3   08-04        3      0.0  24.1   68.0000   0.0  overcast         0.68
4   08-05        4      0.0  24.7   98.0000   0.0     rainy         0.20
5   08-06        5      0.0  26.5   98.0000   0.0       NaN         0.32
6   08-07        6      0.0  27.6   78.0000   0.0     rainy         0.72
7   08-08        0      0.0  28.2   82.1875   0.0     rainy         0.61
8   08-09        1      0.0  27.1   70.0000   0.0  overcast          NaN
9   08-10        2      1.0  26.7   75.0000   NaN     sunny         0.54
11  08-12        4      0.0  24.3   77.0000   0.0  overcast         0.67
12  08-13        5      0.0  23.1   77.0000   1.0     sunny         0.66
13  08-14        6      0.0  22.4   89.0000   1.0     rainy         0.38
14  08-15        0      0.0   NaN   80.0000   1.0     sunny         0.46
15  08-16        1      0.0  26.5   88.0000   1.0     rainy          NaN
16  08-17        2      0.0  28.6   76.0000   0.0       NaN         0.52
18  08-19        4      0.0  27.0   73.0000   1.0  overcast         0.62
19  08-20        5      0.0  26.9   73.0000   0.0     sunny         0.81

#  ❯ Linear Interpolation

![Imgur](https://i.imgur.com/uzKMMZq.png)

In [ ]:
# Linear Interpolation on Temperature
df['Temp'].interpolate(method='linear', inplace=True)

df

     Date  Weekday  Holiday   Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.10   99.0000   0.0     rainy         0.14
1   08-02        1      0.0  26.40   82.1875   0.0     sunny          NaN
2   08-03        2      0.0  25.25   96.0000   0.0     rainy         0.21
3   08-04        3      0.0  24.10   68.0000   0.0  overcast         0.68
4   08-05        4      0.0  24.70   98.0000   0.0     rainy         0.20
5   08-06        5      0.0  26.50   98.0000   0.0       NaN         0.32
6   08-07        6      0.0  27.60   78.0000   0.0     rainy         0.72
7   08-08        0      0.0  28.20   82.1875   0.0     rainy         0.61
8   08-09        1      0.0  27.10   70.0000   0.0  overcast          NaN
9   08-10        2      1.0  26.70   75.0000   NaN     sunny         0.54
11  08-12        4      0.0  24.30   77.0000   0.0  overcast         0.67
12  08-13        5      0.0  23.10   77.0000   1.0     sunny         0.66
13  08-14        6      0.0  22.40   89.0000   1.0     rainy         0.38
14  08-15        0      0.0  24.45   80.0000   1.0     sunny         0.46
15  08-16        1      0.0  26.50   88.0000   1.0     rainy          NaN
16  08-17        2      0.0  28.60   76.0000   0.0       NaN         0.52
18  08-19        4      0.0  27.00   73.0000   1.0  overcast         0.62
19  08-20        5      0.0  26.90   73.0000   0.0     sunny         0.81

#  ❯ Hot-Deck Imputation
![Imgur](https://i.imgur.com/kFVmcXr.png)

In [ ]:
# Hot-Deck Imputation on Outlook
df['Outlook'].fillna(method='ffill', inplace=True)

df

     Date  Weekday  Holiday   Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.10   99.0000   0.0     rainy         0.14
1   08-02        1      0.0  26.40   82.1875   0.0     sunny          NaN
2   08-03        2      0.0  25.25   96.0000   0.0     rainy         0.21
3   08-04        3      0.0  24.10   68.0000   0.0  overcast         0.68
4   08-05        4      0.0  24.70   98.0000   0.0     rainy         0.20
5   08-06        5      0.0  26.50   98.0000   0.0     rainy         0.32
6   08-07        6      0.0  27.60   78.0000   0.0     rainy         0.72
7   08-08        0      0.0  28.20   82.1875   0.0     rainy         0.61
8   08-09        1      0.0  27.10   70.0000   0.0  overcast          NaN
9   08-10        2      1.0  26.70   75.0000   NaN     sunny         0.54
11  08-12        4      0.0  24.30   77.0000   0.0  overcast         0.67
12  08-13        5      0.0  23.10   77.0000   1.0     sunny         0.66
13  08-14        6      0.0  22.40   89.0000   1.0     rainy         0.38
14  08-15        0      0.0  24.45   80.0000   1.0     sunny         0.46
15  08-16        1      0.0  26.50   88.0000   1.0     rainy          NaN
16  08-17        2      0.0  28.60   76.0000   0.0     rainy         0.52
18  08-19        4      0.0  27.00   73.0000   1.0  overcast         0.62
19  08-20        5      0.0  26.90   73.0000   0.0     sunny         0.81

#  ❯ Imputation using Prediction Models
![Imgur](https://i.imgur.com/cH2kQHY.png)

In [ ]:
# Imputation using kNN on Crowdedness
from sklearn.impute import KNNImputer

# Select numerical columns for kNN imputation.
# Other than 'Crowdedness', make sure the other columns missing values are already filled
df_numerical = df[['Holiday', 'Temp', 'Humidity', 'Crowdedness']]

# Perform kNN imputation
imputer = KNNImputer(n_neighbors=3, weights='distance')
df_imputed = imputer.fit_transform(df_numerical)
df[['Holiday', 'Temp', 'Humidity', 'Crowdedness']] = df_imputed.round(2)

df

     Date  Weekday  Holiday   Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.10     99.00   0.0     rainy         0.14
1   08-02        1      0.0  26.40     82.19   0.0     sunny         0.59
2   08-03        2      0.0  25.25     96.00   0.0     rainy         0.21
3   08-04        3      0.0  24.10     68.00   0.0  overcast         0.68
4   08-05        4      0.0  24.70     98.00   0.0     rainy         0.20
5   08-06        5      0.0  26.50     98.00   0.0     rainy         0.32
6   08-07        6      0.0  27.60     78.00   0.0     rainy         0.72
7   08-08        0      0.0  28.20     82.19   0.0     rainy         0.61
8   08-09        1      0.0  27.10     70.00   0.0  overcast         0.70
9   08-10        2      1.0  26.70     75.00   NaN     sunny         0.54
11  08-12        4      0.0  24.30     77.00   0.0  overcast         0.67
12  08-13        5      0.0  23.10     77.00   1.0     sunny         0.66
13  08-14        6      0.0  22.40     89.00   1.0     rainy         0.38
14  08-15        0      0.0  24.45     80.00   1.0     sunny         0.46
15  08-16        1      0.0  26.50     88.00   1.0     rainy         0.41
16  08-17        2      0.0  28.60     76.00   0.0     rainy         0.52
18  08-19        4      0.0  27.00     73.00   1.0  overcast         0.62
19  08-20        5      0.0  26.90     73.00   0.0     sunny         0.81

#  ❯ Imputation using Constant Value
![Imgur](https://i.imgur.com/PK6BBks.png)

In [ ]:
# Replace missing value on Windy with -99
df['Wind'].fillna(-99, inplace=True)

df

     Date  Weekday  Holiday   Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.10     99.00   0.0     rainy         0.14
1   08-02        1      0.0  26.40     82.19   0.0     sunny         0.59
2   08-03        2      0.0  25.25     96.00   0.0     rainy         0.21
3   08-04        3      0.0  24.10     68.00   0.0  overcast         0.68
4   08-05        4      0.0  24.70     98.00   0.0     rainy         0.20
5   08-06        5      0.0  26.50     98.00   0.0     rainy         0.32
6   08-07        6      0.0  27.60     78.00   0.0     rainy         0.72
7   08-08        0      0.0  28.20     82.19   0.0     rainy         0.61
8   08-09        1      0.0  27.10     70.00   0.0  overcast         0.70
9   08-10        2      1.0  26.70     75.00 -99.0     sunny         0.54
11  08-12        4      0.0  24.30     77.00   0.0  overcast         0.67
12  08-13        5      0.0  23.10     77.00   1.0     sunny         0.66
13  08-14        6      0.0  22.40     89.00   1.0     rainy         0.38
14  08-15        0      0.0  24.45     80.00   1.0     sunny         0.46
15  08-16        1      0.0  26.50     88.00   1.0     rainy         0.41
16  08-17        2      0.0  28.60     76.00   0.0     rainy         0.52
18  08-19        4      0.0  27.00     73.00   1.0  overcast         0.62
19  08-20        5      0.0  26.90     73.00   0.0     sunny         0.81

![Imgur](https://i.imgur.com/enMQvuY.png)

In [ ]:
print("Before:")
golf_dataset

Before:

     Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.1      99.0   0.0     rainy         0.14
1   08-02        1      0.0  26.4       NaN   0.0     sunny          NaN
2   08-03        2      0.0   NaN      96.0   0.0     rainy         0.21
3   08-04        3      0.0  24.1      68.0   0.0  overcast         0.68
4   08-05        4      NaN  24.7      98.0   0.0     rainy         0.20
5   08-06        5      0.0  26.5      98.0   0.0       NaN         0.32
6   08-07        6      0.0  27.6      78.0   0.0     rainy         0.72
7   08-08        0      0.0  28.2       NaN   0.0     rainy         0.61
8   08-09        1      0.0  27.1      70.0   0.0  overcast          NaN
9   08-10        2      1.0  26.7      75.0   NaN     sunny         0.54
10  08-11        3      0.0   NaN       NaN   0.0       NaN          NaN
11  08-12        4      NaN  24.3      77.0   0.0  overcast         0.67
12  08-13        5      0.0  23.1      77.0   1.0     sunny         0.66
13  08-14        6      0.0  22.4      89.0   1.0     rainy         0.38
14  08-15        0      0.0   NaN      80.0   1.0     sunny         0.46
15  08-16        1      0.0  26.5      88.0   1.0     rainy          NaN
16  08-17        2      0.0  28.6      76.0   0.0       NaN         0.52
17  08-18        3      0.0   NaN       NaN   NaN     rainy          NaN
18  08-19        4      0.0  27.0      73.0   1.0  overcast         0.62
19  08-20        5      0.0  26.9      73.0   0.0     sunny         0.81

In [ ]:
print("\n\nAfter:")
df

After:

     Date  Weekday  Holiday   Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.10     99.00   0.0     rainy         0.14
1   08-02        1      0.0  26.40     82.19   0.0     sunny         0.59
2   08-03        2      0.0  25.25     96.00   0.0     rainy         0.21
3   08-04        3      0.0  24.10     68.00   0.0  overcast         0.68
4   08-05        4      0.0  24.70     98.00   0.0     rainy         0.20
5   08-06        5      0.0  26.50     98.00   0.0     rainy         0.32
6   08-07        6      0.0  27.60     78.00   0.0     rainy         0.72
7   08-08        0      0.0  28.20     82.19   0.0     rainy         0.61
8   08-09        1      0.0  27.10     70.00   0.0  overcast         0.70
9   08-10        2      1.0  26.70     75.00 -99.0     sunny         0.54
11  08-12        4      0.0  24.30     77.00   0.0  overcast         0.67
12  08-13        5      0.0  23.10     77.00   1.0     sunny         0.66
13  08-14        6      0.0  22.40     89.00   1.0     rainy         0.38
14  08-15        0      0.0  24.45     80.00   1.0     sunny         0.46
15  08-16        1      0.0  26.50     88.00   1.0     rainy         0.41
16  08-17        2      0.0  28.60     76.00   0.0     rainy         0.52
18  08-19        4      0.0  27.00     73.00   1.0  overcast         0.62
19  08-20        5      0.0  26.90     73.00   0.0     sunny         0.81

# Remarks
![Imgur](https://i.imgur.com/LU1PZPZ.png)

![Imgur](https://i.imgur.com/rhybfvB.png)

---

## Series Index

### Current Series: Data Exploration 🔭

Here's the overview of our Data Exploration series on the Golf dataset:

- [x] [⛳️ 02-1・🔍 Data Preprocessing・Introduction](https://www.kaggle.com/code/samybaladram/02-1-data-preprocessing-introduction)
- [x] [⛳️ 02-2・🔍 Data Preprocessing・Missing Values](https://www.kaggle.com/code/samybaladram/02-2-data-preprocessing-missing-values) (◁ You Are Here)
- [ ] [⛳️ 02-3・🔍 Data Preprocessing・Categorical Encoding](https://www.kaggle.com/code/samybaladram/02-3-data-preprocessing-categorical-encoding)
- [ ] [⛳️ 02-4・🔍 Data Preprocessing・Binning](https://www.kaggle.com/code/samybaladram/02-4-data-preprocessing-binning)
- [ ] [⛳️ 02-5・🔍 Data Preprocessing・Scaling](https://www.kaggle.com/code/samybaladram/02-5-data-preprocessing-scaling)

### Full Overview

For a complete list of topics and series, visit the [⛳️ 📋 Table of Contents](https://www.kaggle.com/samybaladram/golf-data-analysis-table-of-contents).



───────────────


**Your Feedback Matters!** 🍃<br>
If you find this notebook useful for your projects or learning, an ⬆️ **upvote** would be appreciated to help others in the community discover it too! (and it's free!)